# Generated by Django 5.0 on 2024-03-30 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_student_f_name_student_l_name_teacher_f_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(null=True, upload_to='companies/'),
        ),
    ]
