# Generated by Django 5.0 on 2024-03-30 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_company_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(default=1, upload_to='companies/'),
            preserve_default=False,
        ),
    ]
